In [21]:
import  numpy as np

In [22]:
arr = np.arange(10)

In [23]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [25]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [26]:
arr2 = np.arange(12).reshape(3,4)

In [27]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
arr2 * arr.sum()

array([[  0,  45,  90, 135],
       [180, 225, 270, 315],
       [360, 405, 450, 495]])

In [31]:
a = np.arange(1,6)
b = np.arange(5,0,-1)

In [32]:
a,b

(array([1, 2, 3, 4, 5]), array([5, 4, 3, 2, 1]))

In [34]:
a.sum() * arr2 +b.sum()

array([[ 15,  30,  45,  60],
       [ 75,  90, 105, 120],
       [135, 150, 165, 180]])